### ISSUE TITLE
Clicking Cancel On Text Editor Font Styles From Ribbon Throws Exception In Query Text Editor

### ISSUE THREAD

**Issue by dragnilar** [dragnilar/Databvase#1]
1. Click "Text Editor Font Styles" on the ribbon
2. Text Editor Font config window appears
3. Click Cancel
```
Result:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Databvase_Winforms.Controls.QueryTextEditor.QueryTextEditor.RegisterSyntaxHighlightingService(Boolean forceExecute) in C:\Users\swhite\source\repos\Databvase-master\Databvase-Winforms\Controls\QueryTextEditor\QueryTextEditor.cs:line 55
   at Databvase_Winforms.Controls.QueryTextEditor.QueryTextEditor.ApplyFontChange() in C:\Users\swhite\source\repos\Databvase-master\Databvase-Winforms\Controls\QueryTextEditor\QueryTextEditor.cs:line 134
   at Databvase_Winforms.Controls.QueryTextEditor.QueryTextEditor.ApplySettingsUpdate(SettingsUpdatedMessage message) in C:\Users\swhite\source\repos\Databvase-master\Databvase-Winforms\Controls\QueryTextEditor\QueryTextEditor.cs:line 127
```

**Comment by dragnilar** [comment]
Caused by not null checking the document in the query text editor. This may be a sign of a disposing issue since this seems to be intermittent.  Added a TODO to come back to this later.
